(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var z2=function(a){a.S("cardstatechange",g.wN(a)&&g.xN(a)?1:0)},nwa=function(a){var b=g.Qh(a);
a=g.Xh(a);return new g.zh(b.x,b.y,a.width,a.height)},owa=function(a){return Math.pow(a,3)},pwa=function(a){return 3*a*a-2*a*a*a},A2=function(a,b){var c=g.Co("use_default_events_client")?void 0:g.sr;
(0,g.y)(b,function(d){d={csn:a,ve:d.getAsJson(),eventType:4};var e={Ik:g.Hs(a),mk:a};"UNDEFINED_CSN"==a?g.Vs("visualElementShown",d,e):c?g.Yp("visualElementShown",d,c,e):g.tr("visualElementShown",d,e)})},B2=function(a,b){var c=g.Co("use_default_events_client")?void 0:g.sr;
(0,g.y)(b,function(d){var e=void 0,f=(e=void 0===e?!1:e)?16:8;d={csn:a,ve:d.getAsJson(),eventType:f};e={Ik:g.Hs(a),mk:a,mG:e};"UNDEFINED_CSN"==a?g.Vs("visualElementHidden",d,e):c?g.Yp("visualElementHidden",d,c,e):g.tr("visualElementHidden",d,e)})},E2=function(a){a=g.Ra(a);
delete C2[a];g.Rb(C2)&&D2&&D2.stop()},rwa=function(){D2||(D2=new g.G(function(){qwa()},20));
var a=D2;a.isActive()||a.start()},qwa=function(){var a=(0,g.E)();
g.Cb(C2,function(b){swa(b,a)});
g.Rb(C2)||rwa()},F2=function(a,b,c,d){g.Mn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.I=b;this.duration=c;this.F=d;this.coords=[];this.progress=this.G=0;this.C=null},swa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.C);a.C=b;twa(a,a.progress);1==a.progress?(a.o=0,E2(a),a.Bd(),a.Hn()):a.sb()&&a.yv()},twa=function(a,b){g.Oa(a.F)&&(b=a.F(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.I[c]-a.A[c])*b+a.A[c]},uwa=function(a,b){g.Re.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.o},G2=function(a,b,c,d,e){F2.call(this,b,c,d,e);
this.element=a},H2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
G2.call(this,a,b,c,d,e)},I2=function(a){g.A.call(this);
this.u=a||window;this.o=[]},J2=function(a){return a.baseUrl||null},K2=function(a,b){return(0,g.De)((0,g.Lc)(a,b,void 0),function(c){return!!c})},vwa=function(a,b,c){function d(Ib){var sb=Ib.hovercardButton;
if(!sb)return null;sb=sb.subscribeButtonRenderer;if(!sb)return null;var te=f(sb.unsubscribedButtonText),bo=f(sb.subscribedButtonText);if(sb.subscribed){var co=f(sb.subscriberCountWithUnsubscribeText);var eo=f(sb.subscriberCountText)}else co=f(sb.subscriberCountText),eo=f(sb.subscriberCountWithSubscribeText);var Aj=null;return Ib.signinEndpoint&&(Aj=g.Mb(Ib,"signinEndpoint","webNavigationEndpointData","url"),!Aj)?null:te&&(bo||Aj)?{subscribed:sb.subscribed,subscribeText:te,subscribeCount:co,unsubscribeText:bo,
unsubscribeCount:eo,enabled:sb.enabled,signinUrl:Aj,classic:Ib.useClassicSubscribeButton}:null}
function e(Ib){if(Ib){var sb=[],te=Ib.videoId;te&&sb.push("v="+te);(te=Ib.playlistId)&&sb.push("list="+te);(Ib=Ib.startTimeSeconds)&&sb.push("t="+Ib);return"/watch?"+sb.join("&")}}
function f(Ib){if(!Ib)return null;var sb=Ib.simpleText;return sb?sb:Ib.runs?(0,g.Lc)(Ib.runs,function(te){return te.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,q=null,r=null,u=null,w=null,B=!1,z=null,D=null,F=null,H=null,V=null;if("VIDEO"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,r=f(b.videoDuration);else if("PLAYLIST"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==h){if(B=g.Mb(l,"browseEndpoint","browseId"))w=B,m="/channel/"+w;n=!1;q="new";(B=!!b.isSubscribe)?z=d(b):D=f(b.subscribersText)}else"WEBSITE"==
h?((F=g.Mb(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(V=f(b.additionalFeesText)),(n=g.Mb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Mb(b,"title","accessibility","accessibilityData","label");var K=b.endpoint?b.endpoint.clickTrackingParams:null,wb="";if(b.metadata){var Hb=f(b.metadata);Hb&&(wb=Hb)}return{id:"element-"+c,type:h,title:f(b.title),metadata:wb,callToAction:f(b.callToAction),
Ny:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:r,playlistLength:u,channelId:w,subscribeButton:z,subscribersText:D,isSubscribe:B,targetUrl:m,DH:n,Cc:{itct:K},eP:q,hm:a?a:null,HH:b.isPlaceholder,impressionUrls:K2(b.impressionUrls||[],J2),uH:K2(b.hovercardShowUrls||[],J2),clickUrls:K2(l.loggingUrls||[],J2),visualElement:g.As(b.trackingParams),productPrice:H,
additionalFeesText:V}},L2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=K2(a.impressionUrls||[],J2);a.trackingParams&&(c.visualElement=g.As(a.trackingParams));c.elements=K2(a.elements||[],function(d,e){return vwa(b,d,e)});
return c},M2=function(a){g.UN.call(this,a);
this.B=this.u=null;this.o={};this.G={};this.F=this.A=null;this.M=[];a=a.O();this.N=g.uy(a)||g.wy(a);this.R=!0;this.I=0;this.C=new g.js(this);g.C(this,this.C);this.C.L(this.player,g.ez("creatorendscreen"),this.kI);this.C.L(this.player,"crx_creatorendscreen",this.lI);this.C.L(this.player,"resize",this.JA);this.C.L(window,"focus",this.YN);this.load();var b=g.xe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Oe(this,function(){g.Ce(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},wwa=function(a){return a.player.getVideoData().fc?"current":a.N?"new":"current"},N2=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},O2=function(a,b,c){c=void 0===c?!0:c;
g.yQ(a.player.app,"creatorendscreen",void 0);a.A&&(a.A.dispose(),a.A=null,a.F.dispose(),a.F=null);for(var d in a.o)a.o[d].dispose();a.o={};a.G={};0<a.M.length&&(a.M.forEach(function(l){l.dispose()}),a.M.length=0);
a.I=0;if((a.u=b)&&b.elements){c&&xwa(a);c=[];d=new g.bz(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.A=new g.U({D:"div",J:"ytp-ce-shadow"}),g.GN(a.player,a.A.element,4),a.F=new g.oO(a.A,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=ywa(a,e);a.o[e.id]=f;a.G[e.id]=e;g.GN(a.player,f.element,4);var h=new g.bz(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);zwa(a,f,e)}g.CN(a.player,c);
a.JA()}},xwa=function(a){var b=g.Es(),c=g.Gs();
c&&b&&a.u.visualElement&&g.at(c,b,a.u.visualElement)},ywa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",W:["ytp-ce-element","ytp-ce-video"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",P:P2(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",P:{href:Q2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",W:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Sn(b.title||"")},V:b.title},{D:"div",J:"ytp-ce-video-duration",V:b.videoDuration}]}]};
c=new g.U(c);break;case "PLAYLIST":c={D:"div",W:["ytp-ce-element","ytp-ce-playlist"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",P:P2(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",P:{href:Q2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",W:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Sn(b.title||"")},V:b.title},{D:"div",J:"ytp-ce-playlist-count",K:[{D:"div",
J:"ytp-ce-playlist-icon"},{D:"div",J:"ytp-ce-playlist-count-text",V:b.playlistLength}]}]}]};c=new g.U(c);break;case "CHANNEL":c={D:"div",W:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",
K:[{D:"div",J:"ytp-ce-expanding-overlay-body",K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",W:["ytp-ce-channel-title","ytp-ce-link"],P:{href:Q2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Sn(b.title||"")},V:b.title},b.subscribeButton?{D:"div",J:"ytp-ce-subscribe-container",K:[{D:"div",J:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",J:"ytp-ce-channel-subscribers-text",V:b.subscribersText}:"",b.metadata?{D:"div",W:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
V:b.metadata}:""]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:P2(b)}]};c=new g.U(c);var d=g.ie(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Cc.itct}else e="endscreen",f=null;e=new g.xP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.M.push(e)}break;case "WEBSITE":c={D:"div",W:["ytp-ce-element","ytp-ce-website"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",K:[{D:"div",J:"ytp-ce-expanding-overlay-body",
K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",J:"ytp-ce-website-title",P:{dir:g.Sn(b.title||"")},V:b.title},{D:"div",J:"ytp-ce-website-metadata",V:b.metadata},{D:"a",W:["ytp-ce-website-goto","ytp-ce-link"],P:{href:Q2(a,b.targetUrl),target:"_blank",tabindex:"-1"},V:b.callToAction}]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:P2(b)},{D:"div",J:"ytp-ce-expanding-icon",P:Awa(b.iconUrl)}]};c=new g.U(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",J:"ytp-ce-merchandise-price-container",
K:[{D:"div",J:"ytp-ce-merchandise-price",V:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",J:"ytp-ce-merchandise-additional-fees",V:b.additionalFeesText})),c={D:"div",W:["ytp-ce-element","ytp-ce-merchandise"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",K:[{D:"div",
J:"ytp-ce-expanding-overlay-body",K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",J:"ytp-ce-merchandise-title",P:{dir:g.Sn(b.title||"")},V:b.title},c,{D:"div",J:"ytp-ce-merchandise-metadata",V:b.metadata},{D:"a",W:["ytp-ce-merchandise-goto","ytp-ce-link"],P:{href:Q2(a,b.targetUrl),target:"_blank",tabindex:"-1"},V:b.callToAction}]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:P2(b)},{D:"div",J:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",J:"ytp-ce-merchandise-invideo-cta",
V:b.callToAction}]}]},c=new g.U(c)}b.HH&&g.I(c.element,"ytp-ce-placeholder");return c},P2=function(a){if(a.Ny)var b=a.Ny.thumbnails;
return Awa(b?b[b.length-1].url:null)},Awa=function(a){return a?{style:"background-image: url("+a+")"}:{}},zwa=function(a,b,c){function d(){h(1)}
function e(){h(-1)}
b.ma("mouseenter",(0,g.x)(a.Tu,a,b,c));b.ma("mouseleave",(0,g.x)(a.Ev,a,b,c));a.player.O().o||b.ma("click",(0,g.x)(function(l){g.I(l.element,"ytp-ce-element-hover")},a,b));
b.ma("click",(0,g.x)(a.UB,a,c));b.ma("keypress",(0,g.x)(a.UB,a,c));b.ma("focus",(0,g.x)(function(l,m){this.Tu(l,m)},a,b,c));
b.ma("blur",(0,g.x)(function(l,m){this.Ev(l,m)},a,b,c));
b.ma("touchstart",(0,g.x)(a.Tu,a,b,c));var f=g.ke("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Kn(b.element,"ytp-ce-element-hover");g.Kn(b.element,"ytp-ce-force-expand")});
b.ma("keydown",(0,g.x)(function(l,m){this.R=9==m.keyCode&&!m.shiftKey},a,b));
var h=(0,g.x)(function(l,m,n){this.I+=n;0<this.I?(g.I(l.element,"ytp-ce-force-expand"),R2(this,m.id,!0)):(g.Kn(l.element,"ytp-ce-force-expand"),g.Kn(l.element,"ytp-ce-element-hover"),R2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ma("blur",g.Sa(function(){"none"!=m.style.display&&a.R&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.ke("ytp-sb-subscribe",b.element));c(g.ke("ytp-sb-unsubscribe",b.element));b.ma("focus",d);b.ma("blur",e)},Q2=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.$y(c)+b}else return"";return b},R2=function(a,b,c){a.A&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.J(a.o[d].element,"ytp-ce-element-shadow-show",c)},S2=function(a,b,c){function d(){f||(e++,e==b.length&&(h.stop(),c&&c()))}
if(!b||0==b.length||N2(a))c&&c();else{b=Bwa(a,b);var e=0,f=!1,h=new g.G(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Hr(b[a],d)}},T2=function(a,b,c){S2(a,b.clickUrls,c);
(a=g.Gs())&&b.DH&&g.bt(a,b.visualElement)},Bwa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Cwa(b[e],c));return d},Cwa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Dwa=function(a){return Array.isArray(a)&&a.length?a[0]:a},U2=function(a){return"string"===typeof a?a:""},V2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Ewa=function(a){this.externalId=a},Fwa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},W2=function(a){return a.value?a.value:null},X2=function(a){if(!a)return null;
var b=g.Fc(U2(a.value));b=g.Bc(b);if(!b)return null;var c=V2(a.target,Gwa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Fwa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Hwa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Kwa=function(a){if(!a)return null;
var b=V2(a.type,Iwa),c=V2(a.trigger,Jwa),d=Dwa(a.url);d=X2(d?d:null);a=Dwa(a.subscribeData);var e=a?a:null;e?(a=U2(e.external_user_id),e=U2(e.subscription_token),a=a&&e?new Ewa(a):null):a=null;return b?new Hwa(b,c,d,a):null},Y2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},Lwa=function(a,b){return g.cb(a.o,b,void 0)},Mwa=function(a,b){this.context=a;
this.o=b},$2=function(a){return a.customMessage?Z2("div","iv-card-message",a.customMessage):""},a3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",J:"iv-card-image",P:{style:c},K:d}},b3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.p(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Z2("li","",c.value));return{D:"ul",J:"iv-card-meta-info",K:b}},Z2=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Sn(c);return{D:a,P:b,V:c}},Nwa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Zo&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Zo+");");c.dir=g.Sn(a.customMessage);var d=[{D:"span",V:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",J:"iv-card-link-icon"}));return{D:"div",W:b,P:c,K:d}},c3=function(a,b,c,d){if(d){b=g.p(b);
for(var e=b.next();!e.done;e=b.next())a.o(e.value,d,c.id,c.Cc,c.ce.click,5)}},Owa=function(a,b){this.merchant=a;
this.price=b},Pwa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Qwa=function(a,b){return b?b:Pwa(a)?"current":"new"},d3=function(a,b){g.A.call(this);
var c=this;this.element=a;this.context=b;this.sa=!1;this.fa=new Map;this.ga=new Map;this.context.H.addEventListener(g.ez("annotations_module"),function(d){(d=c.fa.get(d))&&d.apply(c)});
this.context.H.addEventListener("crx_annotations_module",function(d){(d=c.ga.get(d))&&d.apply(c)})},e3=function(a,b,c,d,e,f,h){a.context.o.ma(b,"click",function(){a.Yu(c,d,e,f||[],h||0)});
a.context.o.ma(b,"touchstart",function(){a.sa=!1});
a.context.o.ma(b,"touchmove",function(){a.sa=!0})},Rwa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},f3=function(a,b,c){return{Uz:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
OD:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
Xr:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},i3=function(a,b,c){d3.call(this,b,c);
var d=this;this.H=a;this.eventId=null;this.Z=this.Ea=this.A=this.Hc=!1;this.aa=null;this.cards=[];this.va=this.I=this.Y=this.C=this.ea=this.o=null;this.N=[];this.G=this.yc=this.T=null;this.F=0;this.U=new g.G(g.Ka,c.B.gb?4E3:3E3);g.C(this,this.U);this.na=new g.G(g.Ka);g.C(this,this.na);this.R=new Mwa(c,function(e,f,h,l,m,n){e3(d,e,f,h,l,m,n)});
this.M=new g.U({D:"div",J:"iv-drawer",P:{id:"iv-drawer"},K:[{D:"div",J:"iv-drawer-header",P:{"aria-role":"heading"},K:[{D:"span",J:"iv-drawer-header-text"},{D:"button",W:["iv-drawer-close-button","ytp-button"],P:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",J:"iv-drawer-content"}]});g.C(this,this.M);this.B=this.M.element;this.ra=new g.oO(this.M,330);g.C(this,this.ra);this.ya=g.ke("iv-drawer-header-text",this.B);this.u=g.ke("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Ea&&g3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ea=d.A)&&h3(d)})},Swa=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){g3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){h3(a)});
var d=c.headerText;g.Ge(a.ya,d);a.I&&a.I.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.T=g.As(c.trackingParams);a.G=g.As(c.closeTrackingParams);a.yc=g.As(c.iconTrackingParams)},Twa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.F;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"simple",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cc:j3(a,c,b,d),sponsored:!1,ce:f3(d,e,d.command),eh:d.trackingParams?g.As(d.trackingParams):null,vf:e.trackingParams?g.As(e.trackingParams):
null,yc:f&&f.trackingParams?g.As(f.trackingParams):null,imageUrl:k3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.S(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Zo:null,title:d.title?g.S(d.title):"",customMessage:d.callToAction?g.S(d.callToAction):"",url:d.command.urlEndpoint.url?X2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:d.command.urlEndpoint.url}):null};l3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.collaboratorInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"collaborator",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cc:j3(a,c,b,d),sponsored:!1,ce:f3(d,e,d.endpoint),eh:d.trackingParams?g.As(d.trackingParams):null,vf:e.trackingParams?g.As(e.trackingParams):null,yc:f&&f.trackingParams?g.As(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,
customMessage:d.customText?g.S(d.customText):null,SC:k3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.S(d.channelName):"",metaInfo:[d.subscriberCountText?g.S(d.subscriberCountText):""],url:X2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};l3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"playlist",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cc:j3(a,c,b,d),sponsored:!1,ce:f3(d,e,d.action),eh:d.trackingParams?g.As(d.trackingParams):null,vf:e.trackingParams?g.As(e.trackingParams):null,yc:f&&f.trackingParams?g.As(f.trackingParams):null,no:k3(d.playlistThumbnail.thumbnails,
258).url,customMessage:d.customMessage?g.S(d.customMessage):null,playlistVideoCount:g.S(d.playlistVideoCount),title:d.playlistTitle?g.S(d.playlistTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.videoCountText?g.S(d.videoCountText):""],url:X2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:Rwa(d.action)})};l3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?
b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"video",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cc:j3(a,c,b,d),sponsored:!1,ce:f3(d,e,d.action),eh:d.trackingParams?g.As(d.trackingParams):null,vf:e.trackingParams?g.As(e.trackingParams):null,yc:f&&f.trackingParams?g.As(f.trackingParams):null,no:k3(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.S(d.lengthString):
null,customMessage:d.customMessage?g.S(d.customMessage):null,title:d.videoTitle?g.S(d.videoTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.viewCountText?g.S(d.viewCountText):""],isLiveNow:!!d.badge,url:X2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:Rwa(d.action)})};l3(a,c)}a.F++},k3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},j3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Vwa=function(a,b){var c=Uwa(a,b);
c&&(c===a.o&&(a.o=null),a.H.removeCueRange(c.card.id),g.Ce(c.it),g.kb(a.cards,c),a.ep(),m3(a))},g3=function(a,b,c){if(!a.A){a.ra.show();
a.ea=new g.G(function(){g.I(a.context.H.getRootNode(),g.fM.IV_DRAWER_OPEN)},0);
a.ea.start();a.aa=g.ip(a.u,"mousewheel",function(h){a.U.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.A=!0;var d=g.Gs();d&&a.T&&a.G&&A2(d,[a.T,a.G]);b={TRIGGER_TYPE:b};for(var e=g.p(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.uA||(f.uA=!0,Wwa(a.context.logger,f.card.ce.Uz,b)),d&&A2(d,[f.card.eh]);z2(a.H);c&&(a.C=new g.G(function(){a.Y=a.I;a.va.focus()},330),a.C.start())}},h3=function(a){a.A&&(a.ra.hide(),g.jp(a.aa),a.aa=null,g.Kn(a.context.H.getRootNode(),g.fM.IV_DRAWER_OPEN),a.A=!1,z2(a.H),a.C&&a.C.stop(),a.C=new g.G(function(){a.Y&&(a.Y.focus(),a.Y=null)},330),a.C.start())},Ywa=function(a){g.Jn(a.xa(),
[g.fM.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.GN(a.H,a.B,5);Xwa(a);a.I=g.ke("ytp-cards-button",a.H.getRootNode());a.va=g.ke("iv-drawer-close-button",a.B);a.Hc=!0},Xwa=function(a){var b=g.ke("iv-drawer-close-button",a.B);
a.context.o.ma(b,"click",a.RF,a);a.context.o.ma(a.u,"touchend",function(){a.U.start()});
a.context.o.ma(a.u,"scroll",a.iG,a);a.context.u.subscribe("onHideControls",function(){a.Z=!0});
a.context.u.subscribe("onShowControls",function(){a.Z=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Z=g.In(a.H.getRootNode(),"ytp-autohide")});
a.N.push(g.To("iv-button-shown",a.MH,a));a.N.push(g.To("iv-button-hidden",a.LH,a));a.N.push(g.To("iv-teaser-shown",a.WI,a));a.N.push(g.To("iv-teaser-hidden",a.NH,a));a.N.push(g.To("iv-teaser-clicked",a.VI,a))},l3=function(a,b){a.Hc||Ywa(a);
Vwa(a,b.id);var c=Zwa(a,b);if(c){var d={card:b,it:c.element,uA:!1},e=$wa(a,d);g.rb(a.cards,e,0,d);c.ba(a.u,e);a.ep();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.A||(a.o=d,m3(a),axa(a,d),g3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.H.getCurrentTime(),5E3>c&&c>b.startMs&&bxa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){bxa(a,d)}),m3(a))}},Zwa=function(a,b){switch(b.type){case "simple":var c=a.R;
var d=b.displayDomain?{D:"div",J:"iv-card-image-text",V:b.displayDomain}:void 0;var e=Nwa(b);d={D:"div",W:["iv-card"],K:[{D:"a",J:"iv-click-target",P:{href:b.url?W2(b.url)||"":""},K:[a3(b.imageUrl,d),{D:"div",J:"iv-card-content",K:[Z2("h2",void 0,b.title),e]}]}]};d=new g.U(d);c3(c,g.je("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.R,d={D:"div",W:["iv-card","iv-card-channel"],K:[{D:"a",W:["iv-click-target"],P:{href:W2(b.url)||"","data-ytid":b.channelId},K:[a3(b.SC),
{D:"div",J:"iv-card-content",K:[$2(b),{D:"h2",J:"iv-card-primary-link",V:b.title},b3(b)]}]}]},d=new g.U(d),c3(c,g.je("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.R,d={D:"div",W:["iv-card","iv-card-playlist"],K:[{D:"a",J:"iv-click-target",P:{href:W2(b.url)||""},K:[a3(b.no,{D:"div",J:"iv-card-image-overlay",K:[{D:"span",J:"iv-card-playlist-video-count",V:b.playlistVideoCount}]}),{D:"div",J:"iv-card-content",K:[$2(b),Z2("h2","iv-card-primary-link",b.title),b3(b)]}]}]},d=new g.U(d),
c3(c,g.je("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.R;var f=!g.gb(b.offers);d=["iv-card"];e="";var h=Nwa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({D:"div",J:"iv-card-offer-price",V:h.price}),h.merchant&&f.push({D:"div",J:"iv-card-offer-merchant",V:h.merchant}),h={D:"div",K:f});f=b.url?W2(b.url)||"":"";d={D:"div",W:d,P:{tabindex:"0"},K:[{D:"a",W:["iv-card-image","iv-click-target"],P:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{D:"div",J:"iv-card-content",K:[b.sponsored?{D:"div",J:"iv-card-sponsored",K:["Sponsored",{D:"div",J:"iv-ad-info-container",K:[{D:"div",J:"iv-ad-info",V:"{{adInfo}}"},{D:"div",J:"iv-ad-info-icon-container",K:[{D:"div",J:"iv-ad-info-icon"},{D:"div",J:"iv-ad-info-callout"}]}]}]}:"",{D:"a",J:"iv-click-target",P:{href:f},K:[Z2("h2",e,b.title),h]}]}]};d=new g.U(d);e=g.xe("span");g.Ge(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Bb(e,"adInfo");c3(c,g.je("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.R,d=b.isLiveNow?{D:"span",W:["yt-badge","yt-badge-live"],V:"LIVE NOW"}:null,d={D:"div",W:["iv-card","iv-card-video"],K:[{D:"a",J:"iv-click-target",P:{href:W2(b.url)||""},K:[a3(b.no,b.videoDuration?{D:"span",J:"iv-card-video-duration",V:b.videoDuration}:void 0),{D:"div",J:"iv-card-content",K:[$2(b),Z2("h2","iv-card-primary-link",b.title),b3(b),d]}]}]},d=new g.U(d),c3(c,g.je("iv-click-target",d.element),
b,b.url),d;default:return null}},$wa=function(a,b){if(0===a.cards.length)return 0;
var c=g.db(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},cxa=function(a){return a.o?"productListing"===a.o.card.type:(0,g.Di)(a.cards,function(b){return"productListing"===b.card.type})},m3=function(a){g.J(a.H.getRootNode(),"ytp-cards-shopping-active",cxa(a))},bxa=function(a,b){if(!g.In(a.H.getRootNode(),"ytp-cards-teaser-shown")){if(a.o!==b){var c=g.Gs(),d=a.o?a.o.card.yc:a.yc;
c&&d&&B2(c,[d]);a.o=b;m3(a)}if(c="none"!=a.xa().style.display)2===a.context.H.getPresentingPlayerType()?c=1===a.context.H.getAdState():(c=a.context.H.getPlayerState(),d=0===c&&0===a.context.H.getCurrentTime(),c=1===c||3===c||d);c&&b.card.teaserDurationMs&&(c={teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs},(d=g.vN(g.kN(a.H)))&&d.Ru(!0,c));a.na.isActive()||((!a.A||!a.U.isActive()&&a.Z)&&axa(a,b),a.na.start(910+b.card.teaserDurationMs))}},axa=function(a,b){if(a.M.La()){var c=new F2([0,
a.u.scrollTop],[0,b.it.offsetTop],600,pwa);a.context.A.ma(c,"animate",function(d){a.u.scrollTop=d.y});
a.context.A.ma(c,"finish",function(d){a.u.scrollTop=d.y});
c.play()}else g.eM(a.M,!0),a.u.scrollTop=b.it.offsetTop,g.eM(a.M,!1)},n3=function(a){return a.o&&a.o.card?a.o.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},Uwa=function(a,b){return g.cb(a.cards,function(c){return c.card.id===b})},o3=function(a,b,c){d3.call(this,a,b);
this.annotation=c;this.isActive=!1},dxa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},p3=function(a,b,c){o3.call(this,a,b,c);
this.u=null;this.G=!1;this.A=null;this.B=!1;this.o=this.F=this.C=null},exa=function(a,b){var c=void 0===c?0:c;
var d=nwa(b).width;g.Mh(b,d);c=new H2(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,owa);g.C(a,c);a.context.A.ma(c,"begin",function(){g.Yh(b,!0)});
c.play()},hxa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
W:["iv-branding-context-name"],V:b.channel_name}),d=a.createElement({D:"div",W:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.o=new g.xP(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.H),a.o.ba(d));var f=a.createElement({D:"div",W:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",W:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Yh(h,!1);var l=a.createElement({D:"div",W:["branding-context-container-outer"]});l.appendChild(h);g.Eh(l,"right",b.image_width+"px");a.xa().appendChild(l);a.A=new g.G(function(){fxa(a,h,l)},500);
g.C(a,a.A);a.context.o.ma(a.xa(),"mouseover",function(){gxa(a,h,l,f,b.image_height)});
a.context.o.ma(a.xa(),"mouseout",function(){a.A.start()})}},gxa=function(a,b,c,d,e){a.A.stop();
if(!a.B){var f=g.Xh(b);a.o||(g.Vh(b,f.width),g.Vh(c,f.width));g.Eh(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Eh(d,"right","1px");a.B=!0;g.Yh(b,!0);a.C=new g.G(function(){g.I(this.xa(),"iv-branding-active")},0,a);
a.C.start()}},fxa=function(a,b,c){g.Kn(a.xa(),"iv-branding-active");
a.F=new g.G(function(){g.Yh(b,!1);a.o||g.Vh(c,0)},250);
a.F.start();a.B=!1},ixa=function(a,b,c,d,e,f,h){this.o=a;
this.A=b;this.B=c;this.videoData=d;this.logger=e;this.H=f;this.u=h},q3=function(a,b,c){o3.call(this,a,b,c);
var d=this;this.I=this.isCollapsed=this.M=!1;this.F=5E3;this.u=this.A=this.o=this.B=null;this.G=this.createElement({D:"div",W:["iv-promo-contents"]});this.C=new g.G(function(){d.o.setAttribute("aria-hidden","true");g.Yh(d.A,!1);g.Yh(d.u,!0)},700,this);
g.C(this,this.C)},jxa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.F=b.collapsedelay_ms||a.F;var d=["iv-promo","iv-promo-inactive"];a.xa().setAttribute("aria-hidden","true");a.xa().setAttribute("aria-label","Promotion");a.xa().tabIndex=0;var e=a.annotation.xc(),f=b.image_url;if(f){var h=a.createElement({D:"div",W:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",P:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({D:"span",J:"iv-promo-video-duration",V:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",J:"iv-promo-playlist-length",V:b.playlist_length.toString()}),h.appendChild(f));e&&e3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",J:"iv-promo-txt"}),g.ed(f,W2(e)),a.o=f):a.o=a.createElement({D:"div",J:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",K:[{D:"strong",V:b.text_line_1}]});
var m=a.createElement({D:"p",K:[{D:"span",J:"iv-promo-link",V:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",W:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",W:["iv-button","iv-promo-button"],K:[{D:"span",J:"iv-button-content",V:f}]});var q=a.createElement({D:"div",J:"iv-promo-button-container"});q.appendChild(f);e&&e3(a,a.xa(),e,a.annotation.id,b.session_data,void 0,c)}g.I(a.o,"iv-click-target");e&&
e3(a,a.o,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",K:[{D:"span",V:b.text_line_1}]}),m=a.createElement({D:"p",K:[{D:"strong",V:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",W:["yt-badge","iv-promo-badge-live"],V:"LIVE NOW"})),g.I(a.o,"iv-click-target"),e&&e3(a,a.o,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.G.appendChild(a.o);q&&a.G.appendChild(q);c=a.createElement({D:"div",
J:"iv-promo-actions"});a.u=a.createElement({D:"button",W:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.o.ma(a.u,"click",function(r){r3(a,5E3,r)});
c.appendChild(a.u);g.Yh(a.u,!1);a.context.o.ma(a.xa(),"mouseover",a.cH,a);a.context.o.ma(a.xa(),"mouseout",a.bH,a);a.context.o.ma(a.xa(),"touchend",function(r){r3(a,5E3,r)});
a.A=a.createElement({D:"button",W:["iv-promo-close","ytp-button"]});a.A.title="Close";a.context.o.ma(a.A,"click","cta"===a.annotation.style&&b.text_line_3?a.VG:a.UG,a);c.appendChild(a.A);g.Jn(a.xa(),d);h&&(a.xa().appendChild(h),n&&h.appendChild(n));a.xa().appendChild(a.G);a.xa().appendChild(c)},r3=function(a,b,c){c.stopPropagation();
kxa(a);lxa(a,b);a.o.focus()},mxa=function(a){a.isCollapsed||a.I||a.B||(g.I(a.xa(),"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},kxa=function(a){a.C.stop();
a.isCollapsed&&(g.Ln(a.xa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.Yh(a.u,!1),g.Yh(a.A,!0))},lxa=function(a,b){a.B||(a.B=g.cg(function(){s3(this);
mxa(this)},b,a))},s3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},nxa=function(a){this.H=a},Wwa=function(a,b,c){b&&(c?t3(a,b.map(function(d){return g.on(d,c)})):t3(a,b))},t3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.p(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Hr(m,f);d&&(e++,0!==d&&a.H.sendVideoStatsEngageEvent(d,f))},u3=function(a){g.UN.call(this,a);
this.N=!1;this.M=0;this.G={};this.Y=new nxa(a);this.C=new g.js(this);g.C(this,this.C);this.F=this.A=null;this.C.L(this.player,"onVideoAreaChange",(0,g.x)(this.S,this,"onVideoAreaChange"));this.C.L(this.player,"onHideControls",(0,g.x)(this.S,this,"onHideControls"));this.C.L(this.player,"onShowControls",(0,g.x)(this.S,this,"onShowControls"));this.C.L(this.player,"resize",(0,g.x)(this.S,this,"resize"));this.C.L(this.player,"presentingplayerstatechange",(0,g.x)(this.S,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.iI,this);this.subscribe("resize",this.rr,this);this.player.O().N.subscribe("vast_info_card_add",this.DC,this);this.T=new g.js(this);g.C(this,this.T);this.U=g.we("DIV","video-custom-annotations");this.u=new g.U({D:"div",W:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.u);g.GN(this.player,this.u.element,4);this.u.hide();this.B=new g.U({D:"div",W:["ytp-iv-video-content"]});g.C(this,this.B);g.ze(this.B.element,g.we("DIV","video-annotations",
this.U));this.I=this.o=null;this.R=[];oxa(this)&&this.load();var b=g.xe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Oe(this,function(){g.Ce(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},pxa=function(){var a=g.we("DIV",["annotation",
"annotation-type-custom"]);g.Yh(a,!1);return a},qxa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},oxa=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.uE||b.N.get(a.videoId)||g.bC(a)||g.cC(a)?!0:!1},rxa=function(a,b){var c=!b.isCued()&&!g.T(b,1024);
g.eM(a.u,c);g.eM(a.B,c)},sxa=function(a,b,c){a.N=!0;
a.F=g.wq(b,c)},txa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(txa(a,e))}return c},uxa=function(a,b,c){return!(a.loaded&&a.M==b&&a.player.getVideoData().videoId==
c)},xxa=function(a){var b=a.player.getVideoData();
if(b.df){var c=a.player.O().N.get(b.videoId);if(c){var d={format:"XML",Ye:{},method:"POST",withCredentials:!0};d.Bd=(0,g.x)(function(e,f,h){uxa(this,e,f)||(e=g.qq(h)&&h.responseXML?h.responseXML:null)&&v3(this,e)},a,a.M,b.videoId);
g.yp()&&(d.Bd=vxa(a,d.Bd));d.Cb={ic_only:"1"};wxa(d,c);a.N=!0;g.wq(b.df,d)}}},wxa=function(a,b){a.method="POST";
a.Cb=a.Cb||{};b.jp&&(a.Cb.ic_coll=b.jp);b.kp&&(a.Cb.ic_xml=b.kp);b.ro&&(a.Cb.ic_track=b.ro)},yxa=function(a){var b=new g.U({D:"div"});
g.Yh(b.element,!1);var c=new i3(a.player,b.element,w3(a));g.C(c,b);b.ba(a.u.element);c.bo();return c},w3=function(a){if(!a.I){var b=new I2(a);
g.C(a,b);var c=new g.y1(a);g.C(a,c);a.I=new ixa(b,c,a.player.O(),a.player.getVideoData(),a.Y,a.player,a.Ea)}return a.I},v3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Gs();if(e){var f=g.Es();f&&g.Ws(g.Co("use_default_events_client")?void 0:g.sr,e,f,[g.As(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=txa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=V2(h.type,zxa),r=V2(h.style,Axa),u=U2(h.data),w=0!=u.length?JSON.parse(u):{};var B=h.action;h=Kwa;if(null==B)var z=null;else if(g.Na(B)){m=[];for(var D=g.p(B),F=D.next();!F.done;F=
D.next()){var H=h(F.value);H&&m.push(H)}z=m}else{var V=h(B);z=V?[V]:[]}f=n&&q?new Y2(n,q,r,z,w):null}else f=null}catch(te){}if(f){a:{switch(f.type){case "branding":case "promotion":h=!0;break a}h=!1}if(h){h=a;m=f;var K=pxa(),wb=null;switch(m.type){case "branding":if(h.player.O().Ha)break;h.u.element.appendChild(K);wb=new p3(K,w3(h),m);break;case "promotion":g.GN(h.player,K,4),wb=new q3(K,w3(h),m)}wb&&wb.bo();if(h=wb)g.C(a,h),a.G[f.id]=h}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=yxa(a),g.C(a,
a.o));if("card"==f.type){c=a.o;var Hb=f&&f.data&&f.data.card_type;h=f.data;if(Hb)switch(m=h.tracking||{},m={Uz:m.impression,click:m.click,close:m.close,OD:m.teaser_impression,Xr:m.teaser_click},K=h.tracking_params||{},wb=null,Hb){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,ce:m,eh:K.card?g.As(K.card):null,vf:K.teaser?
g.As(K.teaser):null,yc:K.icon?g.As(K.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,SC:h.image_url,title:h.title,metaInfo:h.meta_info,url:X2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};l3(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,ce:m,
eh:K.card?g.As(K.card):null,vf:K.teaser?g.As(K.teaser):null,yc:K.icon?g.As(K.icon):null,no:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:X2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};l3(c,f);break;case "productListing":h.signin_url&&(wb=X2({target:"current",value:h.signin_url}));Hb=[];for(var Ib=h.offers||[],sb=0;sb<Ib.length;sb++)Hb.push(new Owa(g.md(Ib[sb].merchant),
g.md(Ib[sb].price)));f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,ce:m,eh:K.card?g.As(K.card):null,vf:K.teaser?g.As(K.teaser):null,yc:K.icon?g.As(K.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,Zo:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?
h.custom_message:null,url:X2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),yU:wb,xU:h.signin_title?h.signin_title:void 0,wU:h.signin_message?h.signin_message:void 0,offers:Hb};l3(c,f);break;case "simple":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,ce:m,eh:K.card?g.As(K.card):null,vf:K.teaser?g.As(K.teaser):
null,yc:K.icon?g.As(K.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,Zo:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:X2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};l3(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||
!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,ce:m,eh:K.card?g.As(K.card):null,vf:K.teaser?g.As(K.teaser):null,yc:K.icon?g.As(K.icon):null,no:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:X2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},l3(c,f)}}else Swa(a.o,f);c=!0}}}c&&(z2(a.player),a.rr())},Bxa=function(a,b){var c=!1;
a.o||(a.o=yxa(a),g.C(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())Twa(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.S(b.headerText):"",g.Ge(c.ya,d),c.I&&c.I.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.T=b.trackingParams?g.As(b.trackingParams):null,c.G=b.closeButton.infoCardIconRenderer.trackingParams?g.As(b.closeButton.infoCardIconRenderer.trackingParams):null,c.yc=b.icon.infoCardIconRenderer.trackingParams?g.As(b.icon.infoCardIconRenderer.trackingParams):
null,z2(a.player),a.rr())},Cxa=function(a,b,c,d,e){if(!a.player.O().Ha){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new Hwa("openUrl","click",new Fwa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.S(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.S(b.subscriberCountText))):(b.subscriberCountText&&(e=g.S(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.S(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.S(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.S(b.subscribedButtonText),unsubscribeCount:h,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new Y2(c,"branding","branding",f,d);d=pxa();a.u.element.appendChild(d);f=new p3(d,w3(a),f);f.bo();g.C(f,f);a.G[c]=f}},vxa=function(a,b){return(0,g.x)(function(){if(!this.ha()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Sa.apply(window,c);this.R.push(g.wp(b))}},a)},C2={},D2=null;g.Ua(F2,g.Mn);g.k=F2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.sb())return!1;E2(this);this.startTime=a=(0,g.E)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.mr();this.ff("play");-1==this.o&&this.ff("resume");this.o=1;var b=g.Ra(this);b in C2||(C2[b]=this);rwa();swa(this,a);return!0};
g.k.stop=function(a){E2(this);this.o=0;a&&(this.progress=1);twa(this,this.progress);this.ff("stop");this.Hn()};
g.k.pause=function(){this.sb()&&(E2(this),this.o=-1,this.ff("pause"))};
g.k.X=function(){0==this.o||this.stop(!1);this.ff("destroy");F2.tc.X.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.yv=function(){this.ff("animate")};
g.k.ff=function(a){this.dispatchEvent(new uwa(a,this))};
g.Ua(uwa,g.Re);g.Ua(G2,F2);G2.prototype.B=g.Ka;G2.prototype.yv=function(){this.B();G2.tc.yv.call(this)};
G2.prototype.Hn=function(){this.B();G2.tc.Hn.call(this)};
G2.prototype.mr=function(){this.B();G2.tc.mr.call(this)};
g.Ua(H2,G2);H2.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.t(I2,g.A);I2.prototype.ma=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.ip(a,b,c);this.o.push(a);return a};
I2.prototype.Lu=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.rp(a,b,c);this.o.push(a);return a};
I2.prototype.ob=function(a){g.jp(a);g.kb(this.o,a)};
I2.prototype.X=function(){g.jp(this.o);this.o.length=0;g.A.prototype.X.call(this)};g.t(M2,g.UN);g.k=M2.prototype;g.k.load=function(){g.UN.prototype.load.call(this);if(!N2(this)){var a=g.aC(this.player.getVideoData());if(a)a=L2(a,wwa(this)),O2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",Bd:(0,g.x)(this.yL,this,a),Ye:{v:a},withCredentials:!0};this.N&&(a.Ye.ptype="embedded");var c=this.player.getVideoData().zp;c&&(a.Cb={ad_tracking:c});if(b=g.$B(b))if(b=g.Fc(b),b=g.Bc(b))this.B=g.wq(b,a)}}};
g.k.unload=function(){O2(this,null);this.B&&(this.B.abort(),this.B=null);g.UN.prototype.unload.call(this)};
g.k.hd=function(a,b){if(!N2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=L2(b,"new");O2(this,c);return!0}return null};
g.k.getOptions=function(){return N2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.yL=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=L2(c,wwa(this)))}O2(this,c)};
g.k.JA=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Dxa.length;f++){var h=Math.abs(b.width-Dxa[f]);if(-1==e||d>=h)e=f,d=h}d=Exa[e];this.A&&g.Eh(this.A.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Wh(e.element,Math.round(h.width*a.width),f);g.Mh(e.element,m,n);g.Ln(e.element,Fxa);m=h.left+h.width/2;h=h.top+l/2;g.I(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Ln(e.element,Exa);g.I(e.element,d);(e=g.ie(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Eh(e,"height",f+"px")}}}}};
g.k.kI=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())S2(this,this.u.impressionUrls),(a=g.Gs())&&this.u.visualElement&&g.Xs(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.I(b,"ytp-ce-shown");S2(this,c.impressionUrls);(b=g.Gs())&&g.Xs(b,c.visualElement);this.player.O().A&&this.player.oa("endscreenelementshown",a)}};
g.k.lI=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.Kn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Kn(b,"ytp-ce-shown");this.player.O().A&&this.player.oa("endscreenelementhidden",a)}};
g.k.YN=function(a){var b=this;a.target===window&&(new g.G(function(){for(var c in b.o)g.Ln(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.UB=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.In(c,"ytp-ce-element");){g.In(c,"subscribe-label")&&T2(this,a);if(g.In(c,"ytp-ce-channel-subscribe"))return;c=g.Ee(c)}if(!c||g.In(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Ev(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.eP?(T2(this,a),this.zD(),this.player.pauseVideo(),c=g.Fc(Q2(this,a.targetUrl)),c=g.Bc(c),g.vO(c,void 0,a.Cc)):(c=this.player.getVideoData().fc,
c=(0,g.x)(this.XO,this,c,Q2(this,a.targetUrl),a.Cc),c=(0,g.x)(this.zD,this,c),T2(this,a,c))}}};
g.k.XO=function(a,b,c){var d=g.eq(b);a&&d&&(d.v||d.list)?g.AU(this.player.app,d.v,c,d.list,!1,void 0):g.uO(b,c)};
g.k.Tu=function(a,b){g.In(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.I(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.G(function(){g.I(a.element,"ytp-ce-element-hover")},200)).start():g.I(a.element,"ytp-ce-element-hover"),S2(this,b.uH),R2(this,b.id,!0))};
g.k.Ev=function(a,b){g.Kn(a.element,"ytp-ce-element-hover");g.Kn(a.element,"ytp-ce-force-expand");R2(this,b.id,!1)};
g.k.zD=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var Dxa=[346,426,470,506,570,640,853,1280,1920],Exa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Fxa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Gwa={OQ:"current",lS:"new"};var Iwa={CLOSE:"close",pS:"openUrl",pF:"subscribe"},Jwa={EQ:"click",CLOSE:"close",wR:"hidden",aT:"rollOut",bT:"rollOver",hT:"shown"};Y2.prototype.xc=function(){var a=Lwa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
var Axa={mQ:"anchored",LE:"branding",CHANNEL:"channel",NQ:"cta",zR:"highlightText",OR:"label",PLAYLIST:"playlist",MS:"popup",nT:"speech",pF:"subscribe",zT:"title",VIDEO:"video",NT:"website"},zxa={LE:"branding",wQ:"card",TQ:"drawer",yR:"highlight",ZR:"marker",RS:"promotion",TEXT:"text",PT:"widget"};g.t(d3,g.A);g.k=d3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.bz(a,b,{id:c});a.namespace="annotations_module";d&&this.fa.set(a,d);e&&this.ga.set(a,e);g.CN(this.context.H,[a])};
g.k.bo=function(){this.context.u.subscribe("resize",this.ep,this)};
g.k.xa=function(){return this.element};
g.k.Yu=function(a,b,c,d,e,f){if(this.sa)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Ce(this.xa())};
g.k.ep=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=W2(a);if(f){var h=Qwa(f,a.target),l=function(){a.o&&e.context.H.pauseVideo();var m=e.context.videoData.fc||!1,n=g.eq(f||"");m&&n&&(n.v||n.list)?g.AU(e.context.H.app,n.v,b,n.list,!1,void 0):g.vO(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);t3(this.context.logger,c,l,d);Pwa(f)||(c=g.Gs(),d=b.itct,c&&d&&g.bt(c,g.As(d)))}};
g.k.X=function(){this.fa.clear();this.ga.clear();g.A.prototype.X.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.C(this,a);return a.element};g.t(i3,d3);g.k=i3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.H.getRootNode())?(a=g.Xh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.ep=function(){var a=this.isAvailable();g.Yh(this.xa(),a);g.J(this.context.H.getRootNode(),g.fM.IV_DRAWER_ENABLED,a);z2(this.H)};
g.k.destroy=function(){var a=g.vN(g.kN(this.H));a&&a.Ru(!1,void 0);try{this.H.getRootNode().removeChild(this.B)}catch(b){}g.Uo(this.N);g.jp(this.aa);this.ea&&this.ea.dispose();this.C&&this.C.dispose();d3.prototype.destroy.call(this)};
g.k.RF=function(){if(this.A){t3(this.context.logger,n3(this).ce.close);var a=g.Gs();a&&this.G&&g.bt(a,this.G);h3(this)}};
g.k.iG=function(){g.J(this.B,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.MH=function(){var a=g.Gs(),b=n3(this);b=b?b.yc:this.yc;a&&b&&A2(a,[b])};
g.k.LH=function(){var a=g.Gs(),b=n3(this);b=b?b.yc:this.yc;a&&b&&B2(a,[b])};
g.k.WI=function(){var a=n3(this);t3(this.context.logger,a.ce.OD);var b=g.Gs();b&&a&&A2(b,[a.vf,a.yc])};
g.k.NH=function(){var a=g.Gs(),b=n3(this);a&&b&&B2(a,[b.vf])};
g.k.VI=function(a){var b=n3(this),c=g.Gs();this.o?a?(a=this.context.logger,t3(a,b.ce.Xr),a.H.sendVideoStatsEngageEvent(4,void 0),c&&b.vf&&g.bt(c,b.vf)):(a=this.context.logger,t3(a,b.ce.Xr),a.H.sendVideoStatsEngageEvent(4,void 0),c&&b.yc&&g.bt(c,b.yc)):(a=this.context.logger,t3(a,b.ce.Xr),a.H.sendVideoStatsEngageEvent(4,void 0),c&&this.yc&&g.bt(c,this.yc))};g.t(o3,d3);o3.prototype.bo=function(){d3.prototype.bo.call(this);dxa(this)};
o3.prototype.show=function(){d3.prototype.show.call(this);var a=g.Gs(),b=this.annotation.data;a&&b&&(b=b.session_data)&&A2(a,[g.As(b.itct)])};
o3.prototype.hide=function(){d3.prototype.hide.call(this);var a=g.Gs(),b=this.annotation.data;a&&b&&(b=b.session_data)&&B2(a,[g.As(b.itct)])};g.t(p3,o3);
p3.prototype.show=function(){if(!this.isActive){o3.prototype.show.call(this);if(!this.G){g.I(this.xa(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({D:"img",W:["branding-img","iv-click-target"],P:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Yh(this.u,!1);var b=this.createElement({D:"div",W:["branding-img-container"]});b.appendChild(this.u);this.xa().appendChild(b);(b=this.annotation.xc())&&e3(this,this.u,b,this.annotation.id,a.session_data);
hxa(this,a);this.G=!0}g.Yh(this.xa(),!0);this.isActive=!0;this.u&&exa(this,this.u)}};
p3.prototype.hide=function(){this.isActive&&(o3.prototype.hide.call(this),g.Yh(this.xa(),!1),this.isActive=!1)};
p3.prototype.destroy=function(){this.o&&(this.o.dispose(),this.o=null);o3.prototype.destroy.call(this)};g.t(q3,o3);g.k=q3.prototype;g.k.show=function(){this.isActive||(o3.prototype.show.call(this),this.M||(jxa(this),this.M=!0),g.Yh(this.xa(),!0),g.cg(function(){g.Kn(this.xa(),"iv-promo-inactive")},100,this),this.xa().removeAttribute("aria-hidden"),this.isActive=!0,s3(this),kxa(this),lxa(this,this.F))};
g.k.hide=function(){this.isActive&&(g.I(this.xa(),"iv-promo-inactive"),this.isActive=!1,this.xa().setAttribute("aria-hidden","true"))};
g.k.Yu=function(a,b,c,d,e,f){return this.isCollapsed?!1:o3.prototype.Yu.call(this,a,b,c,d,e,f)};
g.k.cH=function(a){this.I=!0;r3(this,500,a)};
g.k.bH=function(){this.I=!1;mxa(this)};
g.k.UG=function(a){a.stopPropagation();this.hide()};
g.k.VG=function(a){a.stopPropagation();s3(this);this.isCollapsed=!0;g.I(this.xa(),"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();o3.prototype.destroy.call(this)};g.t(u3,g.UN);g.k=u3.prototype;g.k.hd=function(a,b){if(!qxa(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.x1(b);c&&v3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(Vwa(this.o,b),z2(this.player)),!0}return null};
g.k.getOptions=function(){return qxa(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.rr=function(){if(this.B){var a=g.pN(this.player).getVideoContentRect(!0);g.Wh(this.B.element,a.width,a.height);g.Mh(this.B.element,a.left,a.top)}if(this.o){var b=this.player.Xk();a=this.o;b=b.width;g.J(a.B,"iv-drawer-small",426>=b);g.J(a.B,"iv-drawer-big",1280<=b)}};
g.k.iI=function(a){rxa(this,a.state);g.T(a.state,2)&&(this.pn()&&this.DA()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Ru(!1))};
g.k.load=function(){g.UN.prototype.load.call(this);rxa(this,g.pM(this.player));this.M++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.BL,this,b,this.M),d=(0,g.x)(function(){this.F=null},this);
g.yp()&&(c=vxa(this,c));c={format:"XML",Bd:c,onError:d,Ye:{}};a.isPharma&&(c.Ye.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.O().N.get(b))&&wxa(c,b);b=b&&(b.kp||b.jp);if(!a.Vo||b)a.df?sxa(this,a.df,c):(this.A=(0,g.x)(this.jI,this,c),this.player.addEventListener("videodatachange",this.A));g.GN(this.player,this.B.element,4);this.rr();(b=g.bC(a))&&Bxa(this,b);(b=g.cC(a))&&b.featuredChannel&&Cxa(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.k.jI=function(a){var b=this.player.getVideoData();b.df&&(this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null),sxa(this,b.df,a))};
g.k.unload=function(){g.yQ(this.player.app,"annotations_module",void 0);g.Cb(this.G,function(a){a.destroy()});
this.I=null;this.o&&(this.o.destroy(),this.o=null,z2(this.player));this.N=!1;this.F&&(this.F.abort(),this.F=null);this.G={};this.u.hide();g.UN.prototype.unload.call(this);this.B.detach();this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null)};
g.k.BL=function(a,b,c){this.F=null;!uxa(this,b,a)&&(a=g.qq(c)&&c.responseXML?c.responseXML:null)&&(v3(this,a),g.I(this.player.getRootNode(),"iv-module-loaded"))};
g.k.DC=function(a){a==this.player.getVideoData().videoId&&(this.loaded?xxa(this):this.load())};
g.k.pn=function(){return!!this.o&&this.o.isAvailable()};
g.k.DA=function(){this.pn();return!!this.o&&this.o.A};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.pn();this.o&&(a?c?g3(this.o,c,b):g3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):h3(this.o))};
g.k.Ru=function(a,b){this.player.S(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.X=function(){this.player.O().N.unsubscribe("vast_info_card_add",this.DC,this);g.Kn(this.player.getRootNode(),g.fM.IV_DRAWER_OPEN);for(var a=this.R,b=0,c=a.length;b<c;b++)g.zp(a[b]);this.R.length=0;g.UN.prototype.X.call(this)};g.eO.annotations_module=u3;g.eO.creatorendscreen=M2;})(_yt_player);
