(function(g){var window=this;var xza=function(){return g.X?{D:"div",W:["ytp-icon","ytp-icon-notifications"]}:{D:"svg",P:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},K:[{D:"path",P:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},yza=function(){return g.X?{D:"div",
W:["ytp-icon","ytp-icon-notifications-none"]}:{D:"svg",P:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},K:[{D:"path",P:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},u5=function(a,b){g.OO.call(this,a,{D:"div",
J:"ytp-reminder-menu",P:{role:"menu",tabindex:"-1"},K:[{D:"div",J:"ytp-reminder-menu-contents",K:[{D:"div",J:"ytp-reminder-menu-items"}]}]},100,!0);this.u=b;this.A=[];this.menuPopupRenderer=void 0;this.items=this.ca("ytp-reminder-menu-items");this.hide()},Aza=function(a){var b=zza(a),c=0,d={};
for(c=0;c<b.length;d={Is:d.Is},c++){var e=a.A[c];e||(e=new g.U({D:"div",J:"ytp-reminder-menu-item",P:{role:"menuitem",tabindex:"0"},K:[{D:"div",J:"ytp-reminder-menu-item-icon",V:"{{icon}}"},{D:"div",J:"ytp-reminder-menu-item-label",V:"{{text}}"}]}),d.Is=c,e.ma("click",function(l){return function(){var m=l.Is;a.Sa();m=zza(a)[m];a.S("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.ba(a.items),a.A[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=xza();break;case "NOTIFICATIONS_NONE":h=yza();break;case "NOTIFICATIONS_ACTIVE":h=g.IM()}f=f.text?g.S(f.text):"";e.update({icon:h,text:f})}for(;c<a.A.length;)a.A.pop().dispose();0===c?a.Sa():a.Yb(a.u)},zza=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},v5=function(a){g.U.call(this,{D:"div",
K:[{D:"button",W:["ytp-offline-slate-button","ytp-button"],K:[{D:"div",J:"ytp-offline-slate-button-icon",V:"{{icon}}"},{D:"div",J:"ytp-offline-slate-button-text",V:"{{text}}"}]}]});this.H=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.u=void 0;this.B=this.o=null;(this.C=this.ca("ytp-offline-slate-button"))&&this.L(this.C,"click",this.F);this.hide()},Bza=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=b.toggleButtonRenderer:
b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&c.upcomingEventReminderButtonRenderer?a.upcomingEventReminderButtonRenderer=c.upcomingEventReminderButtonRenderer:c&&c.upcomingEventReminderButtonRenderer||(a.upcomingEventReminderButtonRenderer=null);w5(a)},w5=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.S(b.toggledText):"";a.update({text:c,icon:x5(b.toggledIcon)})}else c=b.defaultText?g.S(b.defaultText):"",a.update({text:c,icon:x5(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=Cza(a))?(c=b.text?g.S(b.text):"",a.update({text:c,icon:x5(b.icon)}),a.show()):a.hide():a.hide()},Eza=function(a,b,c){a.B||(a.B=new g.sr(a.H.O().Y));
var d=g.Pp(a.B.xe||g.Qp());g.Gs()&&(d.context.clientScreenNonce=g.Gs());d.params=c;g.Sp(a.B,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.u&&(a.upcomingEventReminderButtonRenderer.currentState=a.u,a.u=void 0)},
onError:function(){Dza(a)},
Te:function(){Dza(a)}})},Dza=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,w5(a)):a.upcomingEventReminderButtonRenderer&&(a.u=void 0,w5(a))},x5=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return xza();case "NOTIFICATIONS_NONE":return yza();case "NOTIFICATIONS_ACTIVE":return g.IM();default:return null}},Cza=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.u||a.upcomingEventReminderButtonRenderer.currentState;a=g.p(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=c.value.upcomingEventReminderButtonStateRenderer)&&c.state===b&&c.button&&c.button.buttonRenderer)return c.button.buttonRenderer;return null},y5=function(a){g.U.call(this,{D:"div",
J:"ytp-offline-slate",K:[{D:"div",J:"ytp-offline-slate-background"},{D:"div",J:"ytp-offline-slate-bar",K:[{D:"span",J:"ytp-offline-slate-icon",K:[g.X?{D:"div",W:["ytp-icon","ytp-icon-live-icon"]}:{D:"svg",P:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},K:[{D:"path",P:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{D:"circle",P:{cx:"12",cy:"12",r:"3"}}]}]},{D:"span",J:"ytp-offline-slate-messages",K:[{D:"div",J:"ytp-offline-slate-main-text",V:"{{maintext}}"},{D:"div",J:"ytp-offline-slate-subtitle-text",V:"{{subtitletext}}"},{D:"div",J:"ytp-offline-slate-description",V:"{{description}}"}]},{D:"span",J:"ytp-offline-slate-buttons"}]},{D:"button",W:["ytp-offline-slate-close-button","ytp-button"],K:[g.uM()]},{D:"button",W:["ytp-offline-slate-open-button","ytp-button"],K:[g.tM()]},{D:"div",J:"ytp-offline-slate-trailer-chip",
V:"Trailer"}]});var b=this;this.api=a;this.u=this.o=null;this.background=this.ca("ytp-offline-slate-background");this.B=!1;this.A=new g.G(function(){g.I(b.element,"ytp-offline-slate-collapsed")},15E3);
g.C(this,this.A);this.countdownTimer=new g.G(this.gE,1E3,this);this.L(a,"presentingplayerstatechange",this.kE);this.L(a,"livestatedata",this.ka);a=this.ca("ytp-offline-slate-close-button");this.L(a,"click",function(){g.I(b.element,"ytp-offline-slate-collapsed")});
a=this.ca("ytp-offline-slate-open-button");this.L(a,"click",function(){g.Kn(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.ka(a)},z5=function(a,b,c){if(b){var d=null!=b.subtitleText?g.S(b.subtitleText):"";
b=c?c:null!=b.mainText?g.S(b.mainText):"";c=a.getVideoData().shortDescription;a.update({maintext:b,subtitletext:d,description:c});g.J(a.element,"ytp-offline-slate-single-text-line",!d)}},A5=function(a){g.UN.call(this,a);
var b=this;this.G=!1;this.I=0;this.C=!1;this.u=new g.G(function(){var e=b.player.O(),f=b.getVideoData();Fza(b)&&(Gza(b)?(e=g.Fd(b.heartbeatParams.url,{request_id:g.ys()}),f.Fe&&(e=g.Fd(e,{vvt:f.Fe}),f.mdxEnvironment&&(e=g.Fd(e,{mdx_environment:f.mdxEnvironment}))),f.oauthToken&&(e=g.Fd(e,{access_token:f.oauthToken})),Hza(b,f,e)):Iza(b,e,f))},0);
this.o=this.heartbeatParams=null;this.A=!1;this.F=new g.Vn(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.N=new g.sr(void 0);this.utcOffsetMinutes=-(new g.oh).getTimezoneOffset();this.B=new g.js(this);this.M=void 0;g.C(this,this.u);g.C(this,this.B);Jza(this);this.B.L(a,"heartbeatparams",this.FL);this.B.L(a,"presentingplayerstatechange",this.TI);this.B.L(a,"videoplayerreset",this.UI);this.B.L(a,g.ez("heartbeat"),this.SI);this.A&&this.o&&Kza(this,this.o);var c=new g.bz(1E3,0x7ffffffffffff,
{priority:0,namespace:"heartbeat"}),d=new g.bz(0x8000000000000,0x8000000000000,{id:"stream_end",priority:0,namespace:"heartbeat"});g.CN(a,[c,d])},Gza=function(a){var b=a.getVideoData();
return!g.QB(a.getVideoData())||b.Yz?!1:g.Q(a.player.O().experiments,"use_innertube_hearbeats_for_playready")?!!b.lc&&"widevine"===b.lc.flavor:!0},B5=function(a){return Gza(a)?!!a.heartbeatParams:!!a.getVideoData().heartbeatToken},C5=function(a,b){if(!a.u.isActive()&&a.G){var c=a.getVideoData();
if(B5(a)||c.wa)void 0===b&&(b=a.C?a.A?7500:a.heartbeatParams?1E3*a.heartbeatParams.interval:a.getVideoData().Pz||6E4:1E3),a.u.start(b)}},Hza=function(a,b,c){b.an&&(c=g.Fd(c,{internalipoverride:b.an}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.Pf&&(d.kpt=b.Pf);c=g.Fd(c,d);g.wq(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.u.isActive()&&D5(a)){a.F.reset();a.sequenceNumber++;e=e.responseText;var f=Lza(e);if(f){a.player.oa("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(Mza))?"0"===h[1]?0:1:-1;Nza(a,f,e,h)}},
onError:function(e){D5(a)&&E5(a,!0,"net-"+e.status)},
Te:function(){D5(a)&&E5(a,!0,"timeout")},
withCredentials:!0})},D5=function(a){return a.player.da("web_player_heartbeat_should_process_killswitch")||Fza(a)},Fza=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.T(g.pM(a.player,a.getPlayerType()),4)?!1:B5(a)||b.wa?!0:(F5(a),!1)},Iza=function(a,b,c){var d={videoId:c.videoId,
sequenceNumber:a.sequenceNumber},e=g.GI();null==e.user&&(e.user={});null==e.request&&(e.request={});c.mdxEnvironment&&(e.request.mdxEnvironment=c.mdxEnvironment);c.Pf&&(e.user.kidsParent={oauthToken:c.Pf});c.Fe&&(e.user.credentialTransferTokens=[{token:c.Fe,scope:"VIDEO"}]);var f=b.deviceParams,h=b.Y,l={utcOffsetMinutes:a.utcOffsetMinutes};b.experiments.experimentIds&&(l.experimentIds=b.experiments.experimentIds.map(Number));f&&(l.deviceMake=f.cbrand||"www",l.deviceModel=f.cmodel||"www",l.browserName=
f.cbr,l.browserVersion=f.cbrver,l.osName=f.cos,l.osVersion=f.cosver);h&&(l.clientName=h.jl,l.clientVersion=h.innertubeContextClientVersion,l.hl=h.Ym,l.gl=h.Xm);f=a.player.O();f.homeGroupInfo&&(l.homeGroupInfo=JSON.parse(f.homeGroupInfo));if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)l.timeZone=h;f.livingRoomAppMode&&(l.tvAppInfo={livingRoomAppMode:f.livingRoomAppMode});e.client=l;c.contextParams&&(l=c.contextParams)&&(e.activePlayers=[],e.activePlayers.push({playerContextParams:l}));
d.context=e;d.cpn=c.clientPlaybackNonce;e={heartbeatChecks:[]};if(l=c.getPlayerResponse())d.heartbeatToken=c.heartbeatToken,(l=l.playabilityStatus)&&(l=l.liveStreamability)&&l.liveStreamabilityRenderer&&e.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&e.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.Qy(b)&&(e.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),c.fd&&(d.context.client.unpluggedLocationInfo=c.fd),d.context.client.unpluggedAppInfo={enableFilterMode:c.uo},
(b=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(b)&&(l={},l.clientPlayerPositionUtcMillis=""+Math.floor(1E3*b),e.unpluggedParams=l));d.heartbeatRequestParams=e;b={timeout:3E4,onSuccess:function(m){if(!a.u.isActive()&&D5(a)){var n=m.playabilityStatus,q=JSON.stringify(n)||"{}",r=-1,u=m.playabilityStatus;u&&(a.player.oa("onHeartbeat",u),"OK"===u.status?r=m.stopHeartbeat?2:0:"UNPLAYABLE"===u.status?r=1:"LIVE_STREAM_OFFLINE"===u.status&&(r=0));m=r;a.sequenceNumber&&-1===m||a.F.reset();
a.sequenceNumber++;Nza(a,n,q,m)}},
onError:function(m){D5(a)&&E5(a,!0,"net-"+m.status)},
Te:function(){D5(a)&&E5(a,!0,"timeout")}};
c.Xd()&&(b.by="Bearer "+c.Xd());g.Sp(a.N,"player/heartbeat",d,b)},Nza=function(a,b,c,d){if(-1===d)b="decode "+g.Bg(c),E5(a,!1,b);
else if(2===d)F5(a),a.C=!0;else if(a.I=0,a.u.stop(),1===d){a.C=!1;a=a.player;d="LICENSE";var e=Lza(c);e?c=e.reason||g.EO[d]||"":((c=c.match(Mza))&&(c=Number(c[1]))&&(d=g.eG(c)),c=g.EO[d]||"");a.app.A.Oc("heartbeat.stop",c,void 0,void 0);g.tr("heartbeatActionPlayerHalted",Oza(b))}else a.C=!0,c=0,a.A&&b&&(c=Kza(a,b),a.player.S("livestatedata",b)),c?C5(a,c):C5(a)},Kza=function(a,b){var c=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,d=!(!c||!c.switchStreamsImmediately),e=Pza(c),
f=a.getVideoData();
if(g.pM(a.player,a.getPlayerType()).sb()&&!g.YB(f)&&!a.player.isAtLiveHead(a.getPlayerType())&&!d)return e;d=c&&c.streamTransitionEndpoint&&c.streamTransitionEndpoint.watchEndpoint;var h=c&&c.transitionTiming;if(d)if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===h)a.M=d;else if(Qza(a,d))return e;if("OK"===b.status.toUpperCase()){d=c&&c.broadcastId;d=d!==(a.o&&a.o.liveStreamability&&a.o.liveStreamability.liveStreamabilityRenderer&&a.o.liveStreamability.liveStreamabilityRenderer.broadcastId)&&(d||a.player.da("web_player_heartbeat_undefined_killswitch"));
if(!f.hlsvp&&!f.Le||d)return c={video_id:f.videoId},f.mq&&(c.is_live_destination="1"),a.player.da("web_player_heartbeat_request_watch_next")||(c.disable_watch_next=!0,c.raw_watch_next_response=f.Sg),c.autonav_state=f.autonavState,a.kd()&&g.QN(a.player,8),a.player.loadVideoByPlayerVars(c),e;g.DN(a.player,"heartbeat",a.getPlayerType())}c&&c.displayEndscreen&&(f=a.player.O(),a.offlineSlate?(f=a.offlineSlate,f.B=!0,f.La()&&g.aU(f.api.app,void 0)):g.Q(f.experiments,"html5_heartbeat_set_ended")&&g.aU(a.player.app,
void 0));return e},Pza=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},E5=function(a,b,c){if(!a.u.isActive()){a.u.stop();
a.I++;var d=a.getVideoData();(d.Rz||b&&!g.QB(a.getVideoData())&&!B5(a)&&d.wa?0:a.I>=(a.heartbeatParams?a.heartbeatParams.o:d.Qz||5))?(b?(b="heartbeat.net",d={enforcedPolicyToHaltOnNetworkFailure:!0}):(b="heartbeat.servererror",d=Oza()),g.tr("heartbeatActionPlayerHalted",d),(d=a.getVideoData())&&d.wa?a.player.app.A.Oc(b,"Video playback interrupted. Please try again.",c,void 0):a.player.app.A.Oc(b,"Sorry, there was an error licensing this video.",c,void 0)):(C5(a,a.F.getValue()),g.Wn(a.F))}},Oza=function(a){var b=
{enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},F5=function(a){a.I=0;
a.u.stop();a.C=!1;a.sequenceNumber=0},Jza=function(a){var b=a.getVideoData(),c=a.player.O();
if(!b.wa)!g.Q(c.experiments,"html5_release_post_live_heartbeat_killswitch")&&g.fb(b.nd,"heartbeat")&&g.DN(a.player,"heartbeat",a.getPlayerType());else if(!g.Hx(c.B))a.player.app.A.Oc("html5.unsupportedlive","HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1",void 0);else if(g.Q(c.experiments,"live_fresca_v2")){a.A=!0;a.G=!0;if(!g.Ey(c)||g.Qy(c))a.offlineSlate=new y5(a.player),g.C(a,a.offlineSlate),g.GN(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.o=b.playabilityStatus);
a.o?(b=Pza(a.o.liveStreamability&&a.o.liveStreamability.liveStreamabilityRenderer))?C5(a,b):C5(a,7500):C5(a,1E3)}},Qza=function(a,b){var c=b&&b.videoId;
return c?(g.AU(a.player.app,c,void 0,void 0,!0,b),!0):!1},Lza=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}};
g.t(u5,g.OO);u5.prototype.hide=function(){this.u&&this.u.removeAttribute("aria-haspopup");g.OO.prototype.hide.call(this)};
u5.prototype.show=function(){this.u&&this.u.setAttribute("aria-haspopup","true");g.OO.prototype.show.call(this)};
u5.prototype.X=function(){g.Qe(this.A);g.OO.prototype.X.call(this)};g.t(v5,g.U);
v5.prototype.F=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.A(a.toggledServiceEndpoint):this.A(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;w5(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.o&&this.o.La())this.o.Sa();else{var b=Cza(this);b&&this.A(b.serviceEndpoint||b.command);b=g.p(b&&b.command&&b.command.commandExecutorCommand&&b.command.commandExecutorCommand.commands||[]);for(var c=b.next();!c.done;c=b.next())if((c=c.value)&&c.openPopupAction&&
c.openPopupAction.popup&&c.openPopupAction.popup.menuPopupRenderer){a=c.openPopupAction.popup.menuPopupRenderer;break}this.o||(this.o=new u5(this.H,this.C),this.o.ba(this.element),g.C(this,this.o),this.o.subscribe("reminderMenuItemClicked",this.A,this));b=this.o;b.menuPopupRenderer=a;Aza(b)}};
v5.prototype.A=function(a){if(a&&(a.addUpcomingEventReminderEndpoint||a.removeUpcomingEventReminderEndpoint)){if(a.addUpcomingEventReminderEndpoint){var b=a.addUpcomingEventReminderEndpoint;var c="notification/add_upcoming_event_reminder"}else a.removeUpcomingEventReminderEndpoint&&(b=a.removeUpcomingEventReminderEndpoint,c="notification/remove_upcoming_event_reminder");if(c&&b&&b.params)for(Eza(this,c,b.params),a=g.p(b.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&b.updateUpcomingEventReminderButtonStateCommand){this.u=
b.updateUpcomingEventReminderButtonStateCommand.state;w5(this);break}}};g.t(y5,g.U);g.k=y5.prototype;g.k.getPlayerType=function(){if(this.kd())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.kd=function(){return 8===this.api.getPresentingPlayerType()};
g.k.ka=function(a){var b=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate;if(b){this.o=a;b=b.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.gE():z5(this,b);var c=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer.thumbnail;
if(c){var d=0,e=null;c=c.thumbnails;for(var f=0;f<c.length;f++)c[f].width>d&&(d=c[f].width||0,e=c[f].url);e&&(this.background.style.backgroundImage="url("+e+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.u||(this.u=new v5(this.api),this.u.ba(this.ca("ytp-offline-slate-buttons")),g.C(this,this.u)),Bza(this.u,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.u&&Bza(this.u,null,null);this.o=a}else this.o=null;this.kE()};
g.k.kE=function(a){if(this.kd())var b=!0;else{var c=g.pM(this.api),d=this.getVideoData();b=d.wa&&(g.mG(c)||g.T(c,2)||g.T(c,64));var e=2===d.autonavState&&g.T(c,2);c=c.sb()&&!g.YB(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.o&&"LIVE_STREAM_OFFLINE"===this.o.status.toUpperCase()?this.La()?a&&g.qG(a,2)&&(g.Kn(this.element,"ytp-offline-slate-collapsed"),this.A.stop()):(a=this.kd(),g.J(this.element,"ytp-offline-slate-premiere-trailer",a),this.show(),this.A.start(),this.api.S("offlineslatestatechange"),
this.B&&g.aU(this.api.app,void 0)):this.La()&&(this.hide(),this.api.S("offlineslatestatechange"))};
g.k.gE=function(){var a=this.o&&this.o.liveStreamability&&this.o.liveStreamability.liveStreamabilityRenderer&&this.o.liveStreamability.liveStreamabilityRenderer.offlineSlate&&this.o.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer;if(a){var b=Math.floor((0,g.E)()/1E3),c=a.canShowCountdown&&Number(a.scheduledStartTime);!c||c<=b?(z5(this,a),this.countdownTimer.stop()):(b=g.TL(c-b),z5(this,a,b),this.countdownTimer.jb())}};
g.k.X=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.U.prototype.X.call(this)};g.t(A5,g.UN);g.k=A5.prototype;g.k.X=function(){F5(this);g.yQ(this.player.app,"heartbeat",void 0);g.UN.prototype.X.call(this)};
g.k.SI=function(a){this.G=!0;C5(this,2E3);a&&"stream_end"===a.getId()&&Qza(this,this.M)};
g.k.FL=function(a){this.heartbeatParams=a;C5(this,2E3)};
g.k.TI=function(a){this.kd()||(g.T(a.state,2)||g.T(a.state,64)?(F5(this),this.A&&(this.G=!0,C5(this,1E3))):(g.T(a.state,1)||g.T(a.state,8))&&C5(this,2E3))};
g.k.UI=function(){3!==this.player.getPresentingPlayerType()&&C5(this,2E3)};
g.k.getPlayerType=function(){if(this.kd())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.kd=function(){return 8===this.player.getPresentingPlayerType()};
g.k.dg=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.WH=function(){return!!this.offlineSlate&&this.offlineSlate.La()};
var Mza=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.eO.heartbeat=A5;})(_yt_player);
